const PEDIDO_PENDIENTE  = 1
const PEDIDO_PROCESO    = 2
const PEDIDO_ENVIADO    = 3
const PEDIDO_ETREGADO   = 4


module.exports = {
  PEDIDO_PENDIENTE,
  PEDIDO_PROCESO,
  PEDIDO_ENVIADO,
  PEDIDO_ETREGADO
}